# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `FrobulatorService`.
# Please instead update this file by running `bin/tapioca dsl FrobulatorService`.


class FrobulatorService
  class << self
    sig { params(input: ::String, intensity: T.nilable(::Integer)).returns(::ServiceResult) }
    def call(input:, intensity:); end
  end
end
